### PR TITLE
pre trained models doc for metadata

### PR DESCRIPTION
**Pull request by hughes036**
Simple button in models dialog launched our doc hosted in GH:

image

image

TODO

UX review of this feature @thao-do 

Add model metadata content to https://github.com/AllenCell/allencell-segmenter-ml/blob/535-model-metadata/docs/models.md @smishra3 @amilworks

### CODE REVIEW

**Review by saeliddp — APPROVED** [review]

**Comment by thao-do** [comment]
I have a couple recommendations, will get back to you asap

**Comment by smishra3** [comment]
Updated model metadata can be accessed at https://github.com/smishra3/allencell-segmenter-ml/blob/main/docs/models.md

**Comment by hughes036** [comment]
updated the model's doc with content from @smishra3

**Comment by thao-do** [comment]
Hey @hughes036 I'm too late for this - should I move the following to a new feature request ticket? 

Minimum layout recommendation:


Ideal layout recommendation with proper labels:


Icon file, if adding one is problematic, can use existing icon for links or totally omit it:
icon_external-link

**Pull request merged**
